const layouts = {
    qwerty : {
        left_hand :    ["q", "w", "e", "r", "t",
                        "a", "s", "d", "f", "g",
                        "z", "x", "c", "v", "b"],
        right_hand :   ["y", "u", "i", "o", "p",
                        "h", "j", "k", "l",
                        "n", "m"],
        top_row  :      ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
        home_row :      ["a", "s", "d", "f", "g", "h", "j", "k", "l"],
        bottom_row :    ["z", "x", "c", "v", "b", "n", "m"],

        home_position:  ["a", "s", "d", "f", "j", "k", "l"],

        lindex : ["r", "t",
                 "f", "g",
                 "v", "b",],
        rindex : ["y", "u",
                 "h", "j",
                 "n", "m"],
        index : ["r", "t",
                "f", "g",
                "v", "b",
                "y", "u",
                "h", "j",
                "n", "m"],

        lmiddle :["e",
                 "d",
                 "c"],
        rmiddle :["i",
                 "k"],
        middle : ["e", "i",
                  "d", "k",
                  "c", "i",
                  "k"],

        lring :  ["w",
                 "s",
                 "x"],
        rring :  ["o",
                 "l",],
        ring : ["w",
                "s",
                "x", "o",
                "l"],

        lpinky : ["q",
                 "a",
                 "z"],
        rpinky : ["p"],
        pinky : ["q",
                "a",
                "z", "p"]
    },

    qwertz : {
        left_hand :    ["q", "w", "e", "r", "t",
                        "a", "s", "d", "f", "g",
                        "y", "x", "c", "v", "b"],
        right_hand :   ["z", "u", "i", "o", "p",
                        "h", "j", "k", "l",
                        "n", "m"],
        top_row  :      ["q", "w", "e", "r", "t", "z", "u", "i", "o", "p"],
        home_row :      ["a", "s", "d", "f", "g", "h", "j", "k", "l"],
        bottom_row :    ["y", "x", "c", "v", "b", "n", "m"],

        home_position:  ["a", "s", "d", "f", "j", "k", "l"],

        lindex : ["r", "t",
                 "f", "g",
                 "v", "b",],
        rindex : ["z", "u",
                 "h", "j",
                 "n", "m"],
        index : ["r", "t",
                "f", "g",
                "v", "b",
                "z", "u",
                "h", "j",
                "n", "m"],
        
        lmiddle :["e", "i",
                 "d", "k",
                 "c"],
        rmiddle :["i",
                 "k"],
        middle : ["e", "i",
                  "d", "k",
                  "c", "i",
                  "k"],

        lring :  ["w",
                 "s",
                 "x"],
        rring :  ["o",
                 "l",],
        ring : ["w",
                "s",
                "x", "o",
                "l"],
        
        lpinky : ["q",
                 "a",
                 "y"],
        rpinky : ["p"],
        pinky : ["q",
                "a",
                "y", "p"]
    },

    colemak : {
        left_hand :    ["q", "w", "f", "p", "g",
                        "a", "r", "s", "t", "d",
                        "z", "x", "c", "v", "b"],
        right_hand :   ["j", "l", "u", "y", 
                        "h", "n", "e", "i", "o",
                        "k", "m"],
        top_row  :      ["q", "w", "f", "p", "g", "j", "l", "u", "y"],
        home_row :      ["a", "r", "s", "t", "d", "h", "n", "e", "i", "o"],
        bottom_row :    ["z", "x", "c", "v", "b", "k", "m"],

        home_position:  ["a", "r", "s", "t", "n", "e", "i", "o"],

        lindex : ["p", "g",
                 "t", "d",
                 "v", "b"],
        rindex : ["j", "l",
                 "h", "n",
                 "k", "m"],
        index : ["p", "g",
        "t", "d",
        "v", "b","j", "l",
        "h", "n",
        "k", "m"],

        lmiddle :["f",
                 "s",
                 "c"],
        rmiddle :["u",
                 "e"],
        middle : ["f",
                "s",
                "c","u",
                "e"],
            
        lring :  ["w",
                 "r",
                 "x"],
        rring :  ["y",
                 "i"],
        ring : ["w",
                "r",
                "x", "y",
                "i"],
        
        lpinky : ["q",
                 "a",
                 "z"],
        rpinky : ["o"],
        pinky : ["q",
        "a",
        "z", "o"],
    },

    dvorak : {
        left_hand :    [               "p", "y",
                        "a", "o", "e", "u", "i",
                             "q", "j", "k", "x"],
        right_hand :   ["f", "g", "c", "r", "l",
                        "d", "h", "t", "n", "s",
                        "b", "m", "w", "v", "z"],
        top_row  :      ["p", "y", "f", "g", "c", "r", "l"],
        home_row :      ["a", "o", "e", "u", "i", "d", "h", "t", "n", "s"],
        bottom_row :    ["q", "j", "k", "x", "b", "m", "w", "v", "z"],

        home_position:  ["a", "o", "e", "u", "h", "t", "n", "s"],

        lindex : ["p", "y",
                  "u", "i",
                  "k", "x"],
        rindex : ["f", "g",
                  "d", "h",
                  "b", "m"],
        index :  ["p", "y",
                "u", "i",
                "k", "x","f", "g",
                "d", "h",
                "b", "m"],      

        lmiddle :["e",
                  "j",
                    ],
        rmiddle :["c",
                  "t",
                  "w"],
        middle : ["e",
                "j", "c",
                "t",
                "w"],

        lring :  [
                  "o",
                  "q"],
        rring :  ["r",
                  "n",
                  "v"],
        ring : [
            "o",
            "q","r",
            "n",
            "v"],

        lpinky : [
                  "a"
                     ],
        rpinky : ["l",
                  "s",
                  "z"],
        pinky : [
            "a","l",
            "s",
            "z"
               ]
    }
}